# Exercise 09_01 - Error Handling
# Write a function that takes two numbers and returns their division.
# Handle the `ZeroDivisionError` exception if the second number is zero by returning `None`.


def divide(a: int, b: int) -> float | None:
    # Your code should go here.

    return ...
